name: Docker Image build and push

on:
  push:

jobs:
  path-context:
    name: Build and push
    runs-on: docker.pkg.github.com/tobsa13/testaction/test:sha-82bf05f
    steps:
    - name: Checkout
      uses: actions/checkout@v2
